### ISSUE TITLE
Issue with external materialized

### ISSUE THREAD

**Issue by pyjads** [milicevica23/dbt-duckdb-delta-plugin-demo#2]
```
{{ config(
    materialized='external',
    plugin = 'delta',
    location = '/Users/pyjads/dbt_trial/store/dest',
    mode = "overwrite",
    storage_options = {
        "connection_string": "DefaultEndpointsProtocol=https;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;EndpointSuffix=core.windows.net",
    }
) }}

select * from {{ source('external-source','userdata1')}}
```
I get following error
IO Error: Cannot open file "/Users/pyjads/dbt_trial/store/dest": Is a directory

If I am not mistaken, the following script should create the deltalake table at the location.

**Comment by milicevica23** [comment]
Hi @pyjads, 
You should be able to set instead "external" -> "external_table", as here in the example https://github.com/l-mds/demo-dbt-duckdb-delta-plugin/blob/main/dbt_duckdb_delta/models/write/customer_overwrite_azure.sql 

more about the problem can be found here https://github.com/l-mds/demo-dbt-duckdb-delta-plugin/issues/1
or read here https://github.com/duckdb/dbt-duckdb/pull/284

Ultimately this should be possible but currently, i have to refactor the external materialization first

**Comment by pyjads** [comment]
The above code works now with 'external', after installing the respository from the branch [milicevica23:feature/support-delta-plugin-write](https://github.com/milicevica23/dbt-duckdb/tree/feature/support-delta-plugin-write).

Thank you.

**Comment by milicevica23** [comment]
ah yes, in the current dbt-duckdb is just the read part
if you push to the azure then please use external_table materialization for now

i would close this issue, feel free to open another one if you find some problems
